apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Chart.Name}}
  labels:
    app.kubernetes.io/name: {{.Chart.Name}}
    app.kubernetes.io/instance: {{ ignore ".Release.Name" }}
    app.kubernetes.io/managed-by: Tiller
    helm.sh/chart: {{ ignore ".Chart.Name" }}-{{ ignore ".Chart.Version" }}
spec:
  replicas: {{ text "{{ .Values.Deployment[" }}{{ default 0 .Index }}{{ text "].Replicas }}" }}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: {{.Chart.Name}}
      app.kubernetes.io/instance: {{.Chart.Name}}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{.Chart.Name}}
        app.kubernetes.io/instance: {{.Chart.Name}}
    spec:
      containers:
      - name: {{.Chart.Name}}
        image: {{ text "{{ .Values.Deployment[" }}{{ default 0 .Index }}{{ text "].Image.Repository }}" }}:{{ text "{{ .Values.Deployment[" }}{{ default 0 .Index }}{{ text "].Image.Tag }}" }}
        enableServiceLinks: false
        ports:
        - name: http
          containerPort: 80
          protocol: TCP