apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{default .Chart.Name .Deployment.Metadata.Name }}
  labels:
  {{- range $key, $value := .Deployment.Metadata.Labels }}
    {{ $key }}: {{ $value }}
  {{- end }}
spec:
  replicas: {{ text "{{ .Values.Deployment[" }}{{ default 0 .Index }}{{ text "].Replicas }}" }}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: {{.Chart.Name}}
      app.kubernetes.io/instance: {{.Chart.Name}}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{.Chart.Name}}
        app.kubernetes.io/instance: {{.Chart.Name}}
    spec:
      containers:
      - name: {{.Chart.Name}}
        image: {{ text "{{ .Values.Deployment[" }}{{ default 0 .Index }}{{ text "].Image.Repository }}" }}:{{ text "{{ .Values.Deployment[" }}{{ default 0 .Index }}{{ text "].Image.Tag }}" }}
        enableServiceLinks: false
        ports:
        {{- range $key, $value := .Deployment.Ports }}
        - name: {{ $value.Name }}
          containerPort: {{ $value.Port }}
          protocol: {{ $value.Protocol }}
        {{- end }}