apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ default .Chart.Name .Deployment.Metadata.Name }}
  labels:
  {{- range $key, $value := .Deployment.Metadata.Labels }}
    {{ $key }}: {{ $value }}
  {{- end }}
spec:
  replicas: {{ text "{{ default 1 ( index .Values.deployment " }}{{ default 0 .Index }}{{ text ").replicas }}" }}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: {{.Chart.Name}}
      app.kubernetes.io/instance: {{.Chart.Name}}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{.Chart.Name}}
        app.kubernetes.io/instance: {{.Chart.Name}}
    spec:
      containers:
      - name: {{.Chart.Name}}
        image: {{ text "{{ ( index .Values.deployment " }}{{ default 0 .Index }}{{ text ").image.repository }}" }}:{{ text "{{ (index .Values.deployment " }}{{ default 0 .Index }}{{ text ").image.tag }}" }}
        enableServiceLinks: false
        env:
          {{ text "{{- range $key, $value := ( index .Values.deployment "}}{{ default 0 .Index }}{{ text ").env }}" }}
          - name: {{ text "{{ $key }}" }}
            value: {{ text "{{ $value | quote }}" }}
          {{ text "{{- end }}" }}
        ports:
        {{- range $key, $value := .Deployment.Ports }}
        - name: {{ $value.Name }}
          containerPort: {{ $value.Port }}
          protocol: {{ $value.Protocol }}
        {{- end }}
