apiVersion: apps/v1
kind: Deployment
metadata:
    name: {{.chart.name}}
    labels:
      app.kubernetes.io/name: {{.chart.name}}
      app.kubernetes.io/instance: {{.chart.name}}
      app.kubernetes.io/managed-by: Tiller
      helm.sh/chart: {{.chart.name}}-{{.chart.version}}
spec:
    replicas: {{ .deployment.replicaCount }}
    selector:
        matchLabels:
            app.kubernetes.io/name: {{.chart.name}}
            app.kubernetes.io/instance: {{.chart.name}}
    template:
        metadata:
            labels:
                app.kubernetes.io/name: {{.chart.name}}
                app.kubernetes.io/instance: {{.chart.name}}
        spec:
            containers:
                - name: {{.chart.name}}
                  image: "{{ .deployment.image.repository }}:{{ .deployment.image.tag }}"
                  imagePullPolicy: {{ .deployment.image.pullPolicy }}
                  ports:
                      - name: http
                        containerPort: 80
                        protocol: TCP
                  livenessProbe:
                      httpGet:
                          path: /
                          port: http
                  readinessProbe:
                      httpGet:
                          path: /
                          port: http
                  resources:
                {{- toYaml .deployment.resources | nindent 12 }}
                {{- with .deployment.nodeSelector }}
            nodeSelector:
                {{- toYaml . | nindent 8 }}
                {{- end }}
                {{- with .deployment.affinity }}
            affinity:
                {{- toYaml . | nindent 8 }}
                {{- end }}
                {{- with .deployment.tolerations }}
            tolerations:
            {{- toYaml . | nindent 8 }}
        {{- end }}
