apiVersion: apps/v1
kind: Deployment
metadata:
    name: {{.Chart.Name}}
    labels:
        app.kubernetes.io/name: {{.Chart.Name}}
        app.kubernetes.io/instance: {{ ignore ".Release.Name" }}
        app.kubernetes.io/managed-by: Tiller
        helm.sh/chart: {{.Chart.Name}}- {{.Chart.Version}}
spec:
    replicas: {{ ignore ".Deployment.Replicas" }}
    selector:
        matchLabels:
            app.kubernetes.io/name: {{.Chart.Name}}
            app.kubernetes.io/instance: {{.Chart.Name}}
    template:
        metadata:
            labels:
                app.kubernetes.io/name: {{.Chart.Name}}
                app.kubernetes.io/instance: {{.Chart.Name}}
        spec:
            containers:
                - name: {{.Chart.Name}}
                  image: "{{ .Deployment.Image.Repository }}:{{ .Deployment.Image.Tag }}"
                        {{- with .Deployment.Image.PullPolicy }}
                  imagePullPolicy: {{ .Deployment.Image.PullPolicy }}
                        {{- end }}
                  ports:
                      - name: http
                        containerPort: 80
                        protocol: TCP
                  livenessProbe:
                      httpGet:
                          path: /
                          port: http
                  readinessProbe:
                      httpGet:
                          path: /
                          port: http
                        {{- with .Deployment.Resources }}
                  resources:
                    {{- toYaml .Deployment.Resources | nindent 12 }}
                    {{- end }}
                {{- with .Deployment.NodeSelector }}
            nodeSelector:
                {{- toYaml . | nindent 8 }}
                {{- end }}
                {{- with .Deployment.Affinity }}
            affinity:
                {{- toYaml . | nindent 8 }}
                {{- end }}
                {{- with .Deployment.Tolerations }}
            tolerations:
            {{- toYaml . | nindent 8 }}
        {{- end }}