apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ default .Chart.Name .NetworkPolicy.Metadata.Name }}
spec:
  podSelector:
    matchLabels:
    {{- range $key, $value := .NetworkPolicy.Selector.MathLabels }}
      {{ $key }}: {{ $value }}
    {{- end }}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector: {}
  egress:
  - ports:
    - port: 53
      protocol: UDP
    namespaceSelector:
      matchLabels:
        name: kube-system
  - to:
    - ipBlock:
        cidr: 0.0.0.0/0
        except:
        - 10.0.0.0/8  # block access to VPC CIDR
        - 192.168.0.0/16  # block access to VPC CIDR
