apiVersion: v1
kind: Secret
metadata:
  name: {{ default .Chart.Name .Secret.Metadata.Name }}
  labels:
  {{- range $key, $value := .Secret.Metadata.Labels }}
    {{ $key }}: {{ $value }}
  {{- end }}
type: Opaque
data:
  {{- range $key, $value := .Secret.Data }}
  {{ $key }}: {{ $value }}
  {{- end }}
