apiVersion: v1
kind: Service
metadata:
  name: {{.Chart.Name}}
  labels:
    app.kubernetes.io/name: {{.Chart.Name}}
    app.kubernetes.io/instance: {{ ignore ".Release.Name" }}
    app.kubernetes.io/managed-by: Tiller
    helm.sh/chart: {{ ignore ".Chart.Name" }}-{{ ignore ".Chart.Version" }}
spec:
  type: {{ .Service.Type }}
  ports:
  {{- range $key, $value := .Service.Ports }}
  - port: {{ $value.Port }}
    targetPort: {{ $value.Name }}
    name: {{ $value.Name }}
  {{- end }}
  selector:
    app.kubernetes.io/name: {{.Chart.Name}}
    app.kubernetes.io/instance: {{.Chart.Name}}
