apiVersion: v1
kind: Service
metadata:
  name: {{.Chart.Name}}
  labels:
  {{- range $key, $value := .Service.Metadata.Labels }}
    {{ $key }}: {{ $value }}
  {{- end }}
spec:
  type: {{ .Service.Type }}
  ports:
  {{- range $key, $value := .Service.Ports }}
  - port: {{ $value.Port }}
    targetPort: {{ $value.Name }}
    name: {{ $value.Name }}
  {{- end }}
  selector:
  {{- range $key, $value := .Service.Metadata.Labels }}
    {{ $key }}: {{ $value }}
  {{- end }}
