name: {{.Name}}
version: {{.Version}}
description: {{.Description}}
apiVersion: {{.ApiVersion}}
appVersion: {{.AppVersion}}
engine: gotpl # The name of the template engine (optional, defaults to gotpl)
